services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - delegator:/var/lib/postgresql/data

  delegator:
    image: deutschemodelunitednations/delegator:latest
    depends_on:
      - postgres
    ports:
      - 3000:3000
    # if you want to utilize a tasks container you can start the image with this instead
    # command: ["bun", "tasksMain.js"]

    # for config options, please refer to the '/src/config' directory
    # for adapter/hosting options please refer to https://github.com/gornostay25/svelte-adapter-bun?tab=readme-ov-file#desktop_computer-environment-variables
    environment:
      # - PORT=3000
      # - HOST=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      # change this to something long, secure and truly random
      - SECRET=123
      # if your setup supports PROTOCOL_HEADER or HOST_HEADER you don't need to set these
      # please see the adapter/hosting options for more information
      - ORIGIN=https://{your orign}

      # variables which are exposed to the client must be prefixed with PUBLIC_
      - PUBLIC_OIDC_AUTHORITY=https://guard.munify.cloud
      - PUBLIC_OIDC_CLIENT_ID=275671515582758948@dev
      #
      # Please make sure that your OIDC auth provider allows
      #
      # https://{your orign}/auth/login-callback
      # https://{your orign}/auth/logout-callback
      #
      # for login and logout callbacks.
      # You can set those in the redirect settings of your auth provider!

volumes:
  delegator:
