changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: ✨ Features
      labels:
        - 'PR: Feature'
    - title: 🚀 Enhancment
      labels:
        - enhancement
    - title: 🐞 Bug Fixes
      labels:
        - 'PR: Bug'
    - title: 📚 Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - '*' # Catch-all for pull requests that didn't match any of the previous categories
