import prettier from 'eslint-config-prettier';
import js from '@eslint/js';
import { includeIgnoreFile } from '@eslint/compat';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import { fileURLToPath } from 'node:url';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';
const gitignorePath = fileURLToPath(new URL('./.gitignore', import.meta.url));

export default ts.config(
	includeIgnoreFile(gitignorePath),
	// Generated by rumble on every dev server start; never edited by hand.
	{ ignores: ['src/lib/api/rumbleClient/**'] },
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs.recommended,
	prettier,
	...svelte.configs.prettier,
	{
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.node
			}
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		ignores: ['eslint.config.js', 'svelte.config.js'],

		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	},
	{
		// Tests of rune modules are compiled as runes too, but are not named `*.svelte.ts`
		files: ['**/*.svelte.test.ts'],
		languageOptions: {
			globals: {
				$state: 'readonly',
				$derived: 'readonly',
				$effect: 'readonly'
			}
		}
	},
	{
		rules: {
			'@typescript-eslint/no-unused-vars': 'warn',
			'@typescript-eslint/no-explicit-any': 'warn',
			'svelte/no-at-html-tags': 'warn',
			'svelte/valid-compile': 'warn',
			'no-undef': 'warn',
			'no-irregular-whitespace': 'warn',
			'svelte/require-each-key': 'warn',
			'svelte/no-dom-manipulating': 'warn',
			'@typescript-eslint/no-non-null-asserted-optional-chain': 'warn',
			'svelte/no-navigation-without-resolve': 'warn',
			'svelte/prefer-writable-derived': 'warn',
			// New in eslint 10's recommended set. It false-positives on Svelte's
			// `$bindable(<default>)` prop defaults, so keep it advisory.
			'no-useless-assignment': 'warn'
		}
	}
);
