// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navigation: {
		/**
		 * O​v​e​r​v​i​e​w
		 */
		OVERVIEW: string
		/**
		 * P​a​s​t​ ​C​o​n​f​e​r​e​n​c​e​s
		 */
		PAST_PROJECTS: string
		/**
		 * R​e​g​i​s​t​r​a​t​i​o​n
		 */
		REGISTER: string
	}
	profileOptions: {
		/**
		 * P​r​o​f​i​l​e
		 */
		PROFILE: string
		/**
		 * S​w​i​t​c​h​ ​T​h​e​m​e
		 */
		SWITCH_THEME: string
		/**
		 * L​o​g​o​u​t
		 */
		LOGOUT: string
	}
}

export type TranslationFunctions = {
	navigation: {
		/**
		 * Overview
		 */
		OVERVIEW: () => LocalizedString
		/**
		 * Past Conferences
		 */
		PAST_PROJECTS: () => LocalizedString
		/**
		 * Registration
		 */
		REGISTER: () => LocalizedString
	}
	profileOptions: {
		/**
		 * Profile
		 */
		PROFILE: () => LocalizedString
		/**
		 * Switch Theme
		 */
		SWITCH_THEME: () => LocalizedString
		/**
		 * Logout
		 */
		LOGOUT: () => LocalizedString
	}
}

export type Formatters = {}
