enum QuestionFlowState {
  Q_PARTICIPANT_OR_SUPERVISOR,

  Q_SUPERVISOR_USERS_ALREADY_REGISTERED,
  FINAL_SUPERVISOR_ANSWER_WAIT,
  FINAL_SUPERVISOR,

  Q_ROLE,

  Q_DELEGATE_HAVE_PARTNERS,
  Q_PARTNERS_CREATED_DELEGATION,
  
  FINAL_CREATE_DELEGATION,
  FINAL_JOIN_DELEGATION,

  FINAL_INDIVIDUAL,
  FINAL_INDIVIDUAL_DELEGATE
}

export default QuestionFlowState;