query SeatsQuery($conferenceId: String!) @blocking {
	findManyCommittees(where: { conferenceId: { equals: $conferenceId } }) {
		id
		name
		abbreviation
		numOfSeatsPerDelegation
	}
	findManyNations(where: { committees: { some: { conferenceId: { equals: $conferenceId } } } }) {
		alpha2Code
		alpha3Code
		committees {
			id
			numOfSeatsPerDelegation
		}
	}
	findManyDelegations(where: { conferenceId: { equals: $conferenceId } }) {
		id
		assignedNation {
			alpha2Code
			alpha3Code
		}
		members {
			id
			assignedCommittee {
				id
			}
			user {
				id
				given_name
				family_name
			}
			isHeadDelegate
		}
		assignedNation {
			alpha2Code
			alpha3Code
		}
		assignedNonStateActor {
			id
			name
		}
	}
}
