query ConferenceSupervisorsQuery($conferenceId: String!) {
	findManyConferenceSupervisors(where: { conferenceId: { equals: $conferenceId } }) {
		id
		plansOwnAttendenceAtConference
		user {
			family_name
			given_name
		}
		delegations {
			id
		}
	}
}