query ConferenceSupervisorsQuery($conferenceId: String!) {
	findManyConferenceSupervisors(where: { conferenceId: { equals: $conferenceId } }) {
		id
		plansOwnAttendenceAtConference
		user {
			family_name
			given_name
		}
		supervisedDelegationMembers {
			delegation {
				id
			}
		}
		supervisedSingleParticipants {
			id
		}
	}
}
