query GetMyActiveConferencesQuery($userId: String!) {
	findManyConferences(
		where: {
			OR: [
				{ conferenceSupervisors: { some: { userId: { equals: $userId } } } }
				{ delegationMembers: { some: { userId: { equals: $userId } } } }
				{ singleParticipants: { some: { userId: { equals: $userId } } } }
			]
		}
	) {
		id
		title
		startConference
		endConference
		startAssignment
		state
	}
}
