query DelegationAssignmentDataQuery($userId: String!, $conferenceId: String!) {
	findUniqueDelegationMember(
		where: { conferenceId_userId: { conferenceId: $conferenceId, userId: $userId } }
	) {
		id
		isHeadDelegate
		assignedCommittee {
			id
		}
		delegation {
			id
			assignedNation {
				alpha3Code
				alpha2Code
			}
			members {
				id
				user {
					id
					family_name
					given_name
				}
				assignedCommittee {
					id
				}
			}
		}
	}

	findManyCommittees(where: { conferenceId: { equals: $conferenceId } }) {
		id
		abbreviation
		name
		nations {
			alpha3Code
			alpha2Code
		}
		numOfSeatsPerDelegation
	}
}
