query BaseAssignmentDataQuery($conferenceId: String!) {
	findManyDelegations(
		where: { conferenceId: { equals: $conferenceId }, applied: { equals: true } }
	) {
		id
		motivation
		experience
		school
		appliedForRoles {
			id
			rank
			nation {
				alpha3Code
				alpha2Code
			}
			nonStateActor {
				id
				name
				abbreviation
				fontAwesomeIcon
				seatAmount
			}
		}
		members {
			id
			isHeadDelegate
			user {
				id
				family_name
				given_name
				birthday
			}
		}
		supervisors {
			id
			delegations {
				id
			}
			user {
				id
				given_name
				family_name
			}
		}
	}

	findManySingleParticipants(
		where: { conferenceId: { equals: $conferenceId }, applied: { equals: true } }
	) {
		id
		motivation
		school
		experience
		user {
			id
			family_name
			given_name
			birthday
		}
		appliedForRoles {
			id
			fontAwesomeIcon
			name
		}
	}

	findUniqueConference(where: { id: $conferenceId }) {
		id
		title
		nonStateActors {
			id
			name
			fontAwesomeIcon
			abbreviation
			seatAmount
		}
		committees {
			id
			name
			abbreviation
			numOfSeatsPerDelegation
			nations {
				alpha2Code
				alpha3Code
			}
		}
		individualApplicationOptions {
			id
			name
			fontAwesomeIcon
		}
	}
}
