import { devAccountClaims, devAccounts, type DevAccount } from './devAccounts';

/** Marks the start of the generated part of `oidc-mock.yaml`; everything above it is kept. */
const OIDC_MOCK_USERS_MARKER =
	'# --- Generated by `bun run dev:accounts` from src/api/db/seed-data/devAccounts.ts - edit there ---';

/** A single-quoted YAML scalar, the form Prettier leaves alone. */
const scalar = (value: string) => `'${value.replaceAll("'", "''")}'`;

/** The `[Group]` a label starts with, used for the comment lines between groups. */
const groupOf = (account: DevAccount) => /^\[([^\]]+)\]/.exec(account.label)?.[1] ?? '';

/** The `users:` block for oidc-mock.yaml, one entry per dev account, in login-page order. */
function renderOidcMockUsers(accounts: readonly DevAccount[] = devAccounts): string {
	const lines = [OIDC_MOCK_USERS_MARKER, 'users:'];
	let group: string | undefined;
	for (const account of accounts) {
		if (groupOf(account) !== group) {
			// No blank line straight after `users:`, which Prettier would remove again.
			if (group !== undefined) lines.push('');
			group = groupOf(account);
			lines.push(`  # ${group}`);
		}
		const claims = devAccountClaims(account);
		lines.push(
			`  - sub: ${scalar(account.sub)}`,
			`    label: ${scalar(account.label)}`,
			`    description: ${scalar(account.description)}`,
			'    claims:',
			`      email: ${scalar(claims.email)}`,
			`      email_verified: ${claims.email_verified}`,
			`      given_name: ${scalar(claims.given_name)}`,
			`      family_name: ${scalar(claims.family_name)}`,
			`      preferred_username: ${scalar(claims.preferred_username)}`,
			`      locale: ${scalar(claims.locale)}`,
			`      roles: [${claims.roles.map(scalar).join(', ')}]`
		);
	}
	return `${lines.join('\n')}\n`;
}

/** `oidc-mock.yaml` with its generated part replaced, keeping the hand-written header. */
export function withGeneratedUsers(file: string): string {
	const markerAt = file.indexOf(OIDC_MOCK_USERS_MARKER);
	const usersAt = markerAt >= 0 ? markerAt : file.search(/^users:/m);
	const header = usersAt >= 0 ? file.slice(0, usersAt) : `${file.trimEnd()}\n\n`;
	return header + renderOidcMockUsers();
}
