query DashboardSurveyPageQuery($userId: String!, $conferenceId: String!) @blocking {
	findManySurveyQuestions(
		where: { conferenceId: { equals: $conferenceId }, draft: { equals: false } }
	) {
		id
		deadline
		title
		description
		options {
			id
			title
			description
			upperLimit
			countSurveyAnswers
		}
	}
	findManySurveyAnswers(
		where: { question: { conferenceId: { equals: $conferenceId } }, userId: { equals: $userId } }
	) {
		id
		question {
			id
		}
		option {
			id
		}
	}
}
