query MyConferenceparticipationQuery($userId: String!, $conferenceId: String!) {
	findUniqueConference(where: { id: $conferenceId }) {
		id
		title
		info
		linkToPreparationGuide
		state
		startConference
		startAssignment
		endConference
		committees {
			id
			abbreviation
			name
			nations {
				alpha3Code
				alpha2Code
			}
			numOfSeatsPerDelegation
		}
		nonStateActors {
			id
			name
			seatAmount
			description
		}
	}

	findUniqueDelegationMember(
		where: { conferenceId_userId: { conferenceId: $conferenceId, userId: $userId } }
	) {
		id
		isHeadDelegate
		assignedCommittee {
			id
			abbreviation
			name
		}
		delegation {
			id
			entryCode
			school
			experience
			motivation
			applied
			members {
				id
				isHeadDelegate
				user {
					id
					pronouns
					family_name
					given_name
					email
				}
				assignedCommittee {
					id
					abbreviation
					name
				}
			}
			assignedNation {
				alpha3Code
				alpha2Code
			}
			assignedNonStateActor {
				id
				abbreviation
				name
				description
				fontAwesomeIcon
				seatAmount
			}
			appliedForRoles {
				id
				rank
				nonStateActor {
					id
					fontAwesomeIcon
					name
					seatAmount
					description
				}
				nation {
					alpha3Code
					alpha2Code
				}
			}
			supervisors {
				id
				user {
					given_name
					family_name
					pronouns
					email
				}
			}
		}
	}
	findUniqueConferenceSupervisor(
		where: { conferenceId_userId: { conferenceId: $conferenceId, userId: $userId } }
	) {
		id
		plansOwnAttendenceAtConference
		delegations {
			id
			applied
			entryCode
			school
			motivation
			experience
			assignedNation {
				alpha3Code
				alpha2Code
			}
			assignedNonStateActor {
				id
				abbreviation
				name
				description
				fontAwesomeIcon
				seatAmount
			}
			appliedForRoles {
				id
				rank
				nonStateActor {
					id
					name
				}
				nation {
					alpha3Code
					alpha2Code
				}
			}
			supervisors {
				id
				user {
					id
					given_name
					family_name
					email
				}
			}
			members {
				id
				isHeadDelegate
				assignedCommittee {
					id
					abbreviation
					name
				}
				user {
					id
					given_name
					family_name
				}
			}
		}
	}
	findUniqueSingleParticipant(
		where: { conferenceId_userId: { conferenceId: $conferenceId, userId: $userId } }
	) {
		id
		school
		motivation
		experience
		applied
		appliedForRoles {
			id
			name
			description
			fontAwesomeIcon
		}
		assignedRole {
			id
			name
			description
			fontAwesomeIcon
		}
		user {
			id
			given_name
			family_name
			pronouns
		}
	}
}
