query SeatsOfConferenceQuery($conferenceId: String!) {
	findUniqueConference(where: { id: $conferenceId }) {
		id
		title
		committees {
			id
			abbreviation
			name
			nations {
				alpha2Code
				alpha3Code
			}
			numOfSeatsPerDelegation
		}
		nonStateActors {
			id
			abbreviation
			name
			description
			fontAwesomeIcon
			seatAmount
		}
	}
}
