query ConferenceRegistrationQuery($conferenceId: String!, $userId: String!) {
	# findUniqueConference(where: { id: $conferenceId }) {
	# 	id
	# 	title
	# }
	findManyConferenceSupervisors(
		where: { conferenceId: { equals: $conferenceId }, userId: { equals: $userId } }
	) {
		id
	}

	findManyDelegationMembers(
		where: { conferenceId: { equals: $conferenceId }, userId: { equals: $userId } }
	) {
		id
	}
	findManySingleParticipants(
		where: { conferenceId: { equals: $conferenceId }, userId: { equals: $userId } }
	) {
		id
	}
}
