query ConferenceOpenForRegistrationQuery($userId: String!) {
	findManyConferences(orderBy: [{ startConference: asc }]) {
		id
		location
		longTitle
		startAssignment
		startConference
		startRegistration
		title
		website
		endConference
		imageDataURL
		language
	}
	findManyDelegationMembers(where: { userId: { equals: $userId } }) {
		conference {
			id
		}
	}
	findManySingleParticipants(where: { userId: { equals: $userId } }) {
		conference {
			id
		}
	}
}
